version: '3.8'

services:
  backend:
    build:
      context: ./reclame-ali-backend
      dockerfile: Dockerfile
    container_name: reclame-ali-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reclame_ali_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./reclame-ali-frontend
      dockerfile: Dockerfile
    container_name: reclame-ali-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: reclame-ali-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: reclame_ali_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysq
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      timeout: 20s
      retries: 10
      interval: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  db_data: